# Generated by Django 3.2.16 on 2023-02-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_offer_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
    ]
