# Generated by Django 3.2.16 on 2023-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_offer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
